name: Bart Roovers
favicon: null
layout_spectrum: 0.9752897743601352
typography_spectrum: 0.38507682643830776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6706740939989686
  lightness: 0.25216220575384796
  saturation: 0.7511611706577241
  rhythmicContrast: 0.010911737103015184
purpose: []
